### ISSUE TITLE
Duplicate PRs created

### ISSUE THREAD

**Issue by austinbutler** [nix-community/nixpkgs-update#284]
- https://github.com/NixOS/nixpkgs/pull/139719
- https://github.com/NixOS/nixpkgs/pull/139725

**Comment by jfly** [comment]
Any update here? I see another example of this:

- https://github.com/NixOS/nixpkgs/pull/304676
- https://github.com/NixOS/nixpkgs/pull/303629

**Comment by rhendric** [comment]
Those PRs target different attribute paths, so that would be more of an example of #315, I think. We still don't have a good way to deduplicate those.

I'm going to close this because I think the original issue of duplicate PRs with the same attribute path has been fixed for a little while.
