### ISSUE TITLE
When an attr begins with a number, add a `_`

### ISSUE THREAD

**Issue by Artturin** [nix-community/nixpkgs-update#369]
Attributes cannot begin with a number so in nixpkgs a `_` is added to the beginning of them

For example `1password` is `_1password`

https://r.ryantm.com/log/1password/2023-03-25.log

```
1password 8.10.1-19.BETA -> 8.10.3 https://repology.org/metapackage/1password/versions
attrpath: 1password
Received ExitFailure 1 when running
Raw command: /nix/store/3nqhcyc7vid1npgcd0m7arg5sn325nhz-nix-2.12.0/bin/nix eval .#1password --apply "p: builtins.hasAttr \"updateScript\" p"
Standard error:

error: flake 'git+file:///var/cache/nixpkgs-update/worker/worktree/1password' does not provide attribute 'packages.x86_64-linux.1password', 'legacyPackages.x86_64-linux.1password' or '1password'
       Did you mean _1password?
```

**Comment by rhendric** [comment]
Are there more recent occurrences of this? I think this was fixed in #345.

**Comment by Artturin** [comment]
Top 4 _ on https://r.ryantm.com/log/ are all old and there's no `._`

**Comment by rhendric** [comment]
These were all written to this month:
* https://r.ryantm.com/log/_1password-gui/
* https://r.ryantm.com/log/_20kly/
* https://r.ryantm.com/log/_7kaa/
* https://r.ryantm.com/log/_7zz/
* https://r.ryantm.com/log/_86Box/
* https://r.ryantm.com/log/_9pfs/

**Comment by Artturin** [comment]
Ahh then the ones at the top are old https://r.ryantm.com/log/1password/

Can they be removed?

**Comment by rhendric** [comment]
If we do something about those old paths, it would be consistent to do the same thing to all the `python3.xx-foo` paths that are now mostly `python3xxPackages.foo`; pretty sure there are more such patterns but other than an age heuristic I don't know how best to find them all.

(The literal answer to ‘can’ is yes, but the implied ‘should’ and ‘would’ are for @ryantm to answer/do.)

**Comment by zowoq** [comment]
We've been deleting build logs older than 18 mothns for a while now so I think this can be closed?
