### ISSUE TITLE
Run nixpkgs-review with `NIXPKGS_ALLOW_INSECURE=1`

### ISSUE THREAD

**Issue by dotlambda** [nix-community/nixpkgs-update#385]
That would allow nixpkgs-update to e.g. build `home-assistant-component-tests`.

**Comment by mweinelt** [comment]
Committers keep on breaking home-assistant in various ways due to r-ryantm proposing updates and not building these tests.

**Comment by dotlambda** [comment]
@Mic92 Would it be reasonable to make nixpkgs-review always build insecure and/or unfree packages?

**Comment by zowoq** [comment]
I've deployed https://github.com/ryantm/nixpkgs-update/pull/391.

**Comment by zowoq** [comment]
Is this still needed after https://github.com/NixOS/nixpkgs/pull/292076?

**Comment by mweinelt** [comment]
Not for home-assistant, but probably for other packages. https://github.com/NixOS/nixpkgs/issues/269713
