### ISSUE TITLE
False update suggested for Elixir 1.16

### ISSUE THREAD

**Issue by ankhers** [nix-community/nixpkgs-update#428]
There was an update suggested for [Elixir](https://github.com/NixOS/nixpkgs/pull/321391) recently. This attempted to update the 1.16 package to be 1.17. The problem being that we obviously want to keep the 1.16 package around without actually updating that to 1.17.

Is there something that we can do in order to prevent this kind of false update from happening? I would be more than happy to put the time in to work on it.

**Comment by rhendric** [comment]
Would it work to give the Elixir packages explicit update scripts that restrict to the intended version ranges?

**Comment by ankhers** [comment]
If that is how it normally works, I would be happy to do this. Do you have an example to point to?

**Comment by rhendric** [comment]
Like this?

https://github.com/NixOS/nixpkgs/blob/7d18aa634e3defec3b3ae10bea469a2693e44d1b/pkgs/applications/misc/pwsafe/default.nix#L100
