### ISSUE TITLE
repology version is wrong

### ISSUE THREAD

**Issue by michaelglass** [nix-community/nixpkgs-update#433]
howdy!

in [these logs](https://nixpkgs-update-logs.nix-community.org/mydumper/2024-07-05.log) the version grabbed (0.16.3_6) isn't the same one on github.

Is there a way to nudge `nixpkgs-update` to use github releases directly?

**Comment by rhendric** [comment]
You can add an update script, as documented [here](https://nixos.org/manual/nixpkgs/stable/#var-passthru-updateScript). Repology versions and other heuristics are only used if there is no explicit update script.
