### ISSUE TITLE
Failed to fetch with source-github command

### ISSUE THREAD

**Issue by spk** [nix-community/nixpkgs-update#438]
I'm trying to setup auto update for https://github.com/platformsh/cli tool the updateScript was recently merged on https://github.com/NixOS/nixpkgs/pull/317185 but I still don't see update PR on https://github.com/NixOS/nixpkgs/pulls/r-ryantm

I've found out with the [doc](https://nix-community.github.io/nixpkgs-update/batch-updates/#batch-updates) that github release can be used to fetch new versions.

I could generate the [packages-to-update.txt](https://github.com/user-attachments/files/16563330/packages-to-update.txt) for the package I'm interested about but when I run `./result/bin/nixpkgs-update source-github` from latest commit 503f7b0 I got an error `Failed to fetch.`

**Comment by rhendric** [comment]
Your update script ran [last Friday](https://nixpkgs-update-logs.nix-community.org/platformsh/2024-08-02.log); everything appears to be in order (there were no new releases at that time). It currently takes about a week before the bot gets around to re-checking packages it has checked recently.
