### ISSUE TITLE
[docs]: what does it do and how?

### ISSUE THREAD

**Issue by con-f-use** [nix-community/nixpkgs-update#445]
The docs could use more details on how nixpkgs-update works. For instance, I haven't been able to answer the question, how it finds updates for python packages and where it searches. Many of them are updated by the bot, yet do not have a `passthru.updateScript` attribute. So a high level overview on what it runs, how it finds updates and for what, would be nice in the documentation, if one want's to be sure that their packages benefit from it.

**Comment by rhendric** [comment]
> Many of them are updated by the bot, yet not `passthru.updateScript` attribute.

Python packages do have a `passthru.updateScript` attribute. Just pull one up in a REPL and check for yourself.

**Comment by con-f-use** [comment]
Yes, some do. Yet e.g. [this update](https://github.com/NixOS/nixpkgs/pull/344910) was apparently performed by the updater, but has no `updateScript`. Or am I wrong?

**Comment by rhendric** [comment]
```
nix-repl> python312Packages.pypck.passthru.updateScript
[ «derivation /nix/store/8d2a01dgdminjczv2jqc5xi4z7k6w9ml-update-python-libraries.drv» "/nix/store/0pgv8qzissxvqgcw2aw1q41qbkqzbj3x-nixos-24.05/nixos/pkgs/development/python-modules/pypck/default.nix" ]
```

**Comment by con-f-use** [comment]
Okay, but where does it come from, if it's not defined in the file https://github.com/NixOS/nixpkgs/blob/cf7cf74b9bc568c902952ceb05c5d603d3b3780a/pkgs/development/python-modules/pypck/default.nix ? I'm just saying, the basic theory of operation should ideally be in the documentation, no?

**Comment by rhendric** [comment]
Valid question, but not for this project. If there's an update script, nixpkgs-update uses it; how it got there is a Nixpkgs question.

**Comment by con-f-use** [comment]
Fair enough, for what it worth,  I found where [`passthru.updateScript`](https://github.com/NixOS/nixpkgs/blob/760c41ba9dcc41622b7d264453473d1b8d2ff3ce/pkgs/development/interpreters/python/mk-python-derivation.nix#L223) comes from and the actual [update script](https://github.com/NixOS/nixpkgs/blob/760c41ba9dcc41622b7d264453473d1b8d2ff3ce/pkgs/development/interpreters/python/update-python-libraries/update-python-libraries.py#L9) as well as a [couple](https://nixos.org/manual/nixpkgs/stable/#python-package-bulk-updates) of [manual](https://nixos.org/manual/nixpkgs/stable/#var-passthru-updateScript-execution) [sections](https://nixos.org/manual/nixpkgs/stable/#var-passthru-updateScript) complete with broken links :wink:. Maybe one or two of those links wouldn't hurt nixpkgs-update's docs, nonetheless.
