### ISSUE TITLE
Package `git-town` not updating

### ISSUE THREAD

**Issue by futile** [nix-community/nixpkgs-update#450]
The package `git-town` in nixpkgs is still at 16.3.0: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/version-management/git-town/default.nix

The upstream is already at 16.4.1:
* upstream: https://github.com/git-town/git-town/releases/tag/v16.4.1
* repology: https://repology.org/project/git-town/versions

There is no open or merged PR for any version after 16.3.0 open at nixpkgs: https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+git-town

The latest logs are for the successful update to 16.3.0, which was on 2024-10-01: https://nixpkgs-update-logs.nix-community.org/git-town/

I couldn't figure out why the package isn't updating anymore, so I'm asking here, hope that is fine!

Thanks a lot!

**Comment by rhendric** [comment]
Under current load conditions, r-ryantm can only look at packages about twice a month, so sadly this isn't terribly unexpected.

Good news, though: `git-town` looks to be number 242 in the queue (out of 17779), and 832 packages have been processed in the past 24 hours. Today may be your lucky day!

**Comment by futile** [comment]
Awesome, thanks! Can I view the queue somewhere as well?

**Comment by rhendric** [comment]
:sweat_smile: You *can*, as it it is technically possible for you to download the supervisor SQLite state database from https://nixpkgs-update-logs.nix-community.org/~supervisor/state.db and issue the appropriate queries against it (after having studied https://github.com/nix-community/infra/blob/master/hosts/build02/supervisor.py to understand the queue schema). But it's not exactly end-user friendly at the moment. (Some day I may publish a dashboard.)

**Comment by futile** [comment]
Aight, got it, thanks for checking! :)

And thanks for your work on r-ryantm and nixpkgs in general! :)

**Comment by futile** [comment]
The PR at nixpkgs is up, so it worked out fine! Thanks a lot again! :)
