### ISSUE TITLE
Question - How to retry or trigger a new build for a broken package?

### ISSUE THREAD

**Issue by cristianoliveira** [nix-community/nixpkgs-update#451]
Hello there!

I noticed that I have broken the default nix build by adding e2e & integration tests to my CLI ([funzzy](https://github.com/cristianoliveira/funzzy)). On the repo, I configured to [only run the unit test](https://github.com/cristianoliveira/funzzy/blob/v1.4.0/nix/package.nix#L18) while building with nix.

Here is the log of the failure https://nixpkgs-update-logs.nix-community.org/funzzy/2024-10-09.log
In the latest version 1.5.0, I have fixed it.

I ran `nixpkgs-update update "funzzy 1.2.0 1.5.0 https://github.com/cristianoliveira/funzzy/releases"` and it built successfully!

```
For attrpath funzzy, using log file: /run/user/1000/nixpkgs-update/funzzy/2024-10-27.log
funzzy 1.2.0 -> 1.5.0 https://github.com/cristianoliveira/funzzy/releases
attrpath: funzzy
[version]
[version] generic version rewriter does not support multiple hashes
[rustCrateVersion]
[rustCrateVersion] Replacing cargoHash with sha256-DJGpNuRb0bFdXBV/p3enyTvZgJIQOaNy3kijxuLFl1g=
^A[rustCrateVersion] Finished updating Crate version and replacing hashes
[golangModuleVersion]
[golangModuleVersion] Not a buildGoModule package with vendorSha256 or vendorHash
[npmDepsVersion]
[npmDepsVersion] No npmDepsHash
[updateScript]
[updateScript] skipping because derivation has no updateScript
Diff after rewrites:
diff --git a/pkgs/development/tools/misc/funzzy/default.nix b/pkgs/development/tools/misc/funzzy/default.nix
index c1f4b642a86f..a5b830a87478 100644
--- a/pkgs/development/tools/misc/funzzy/default.nix
+++ b/pkgs/development/tools/misc/funzzy/default.nix
@@ -7,16 +7,16 @@

 rustPlatform.buildRustPackage rec {
   pname = "funzzy";
-  version = "1.2.0";
+  version = "1.5.0";

   src = fetchFromGitHub {
     owner = "cristianoliveira";
     repo = "funzzy";
     rev = "v${version}";
-    hash = "sha256-YjA/XxVB8gGxyLovxTTatSC/ESBCkgz7Not0qfEPxtw=";
+    hash = "sha256-3EHZvgHlM3ldX6SEyqGf6MZIrDFOLXbKTZnJNczT570=";
   };

-  cargoHash = "sha256-eq5d6oHWKip9K+9yszLXW+JHtzYzrThXfqoZGMhnSHk=";
+  cargoHash = "sha256-DJGpNuRb0bFdXBV/p3enyTvZgJIQOaNy3kijxuLFl1g=";

   buildInputs = lib.optionals stdenv.hostPlatform.isDarwin [
     darwin.apple_sdk.frameworks.CoreServices

Successfully finished processing
...
```

So now how could I trigger for the bot to retry?

Thanks for your work!

**Comment by cristianoliveira** [comment]
I'm not sure how to trigger the bot, but it seem that it has ran and is working :tada: 
https://github.com/NixOS/nixpkgs/pull/359398

Thanks!

**Comment by croissong** [comment]
@cristianoliveira I am still interested in an answer, because it can take a long time before the bot is re-triggered (another example: https://r.ryantm.com/log/updatecli/).
Would you mind reopening the issue? :pray:

**Comment by zowoq** [comment]
> So now how could I trigger for the bot to retry?

You can't trigger a retry.

> it can take a long time before the bot is re-triggered

Normally it may take a week or so before it would be retried but because of CI problems there is a large backlog that it is currently working through, will hopefully be back to normal in another week or so.
