### ISSUE TITLE
The bot should use "→" instead of "->"

### ISSUE THREAD

**Issue by samueltardieu** [nix-community/nixpkgs-update#452]
When upgrading a package, the bot should use "→" instead of "->". This is prettier, and [is an accepted practice](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions).

**Comment by zowoq** [comment]
> is an accepted practice

"also accepted", it isn't the default.

Update the docs and `maintainers/scripts/update.py` to make it the default and then we can change it here.

**Comment by jtojnar** [comment]
See https://github.com/NixOS/nixpkgs/pull/225965 for the latter.
