### ISSUE TITLE
Bot re-requests reviews

### ISSUE THREAD

**Issue by aidalgol** [nix-community/nixpkgs-update#456]
Sometimes there is a long delay between the bot creating a PR with maintainer pings and requesting reviews from maintainers.  If a maintainer approves such a PR upon noticing the ping but before the bot requests a review, the bot will re-request reviews from all maintainers, thus clearing all maintainer approvals from the PR.

**Comment by zowoq** [comment]
The bot only ping maintainers, it doesn't request reviews?

**Comment by aidalgol** [comment]
Oh, sorry, it's a different bot requesting the reviews: ofborg.
